In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame([1,2,3],[4,5,6])

## Array Basics

In [7]:
##creating arrays
a = np.array([1, 2, 3, 4])              # from a list
b = np.array([[1, 2], [3, 4]])          # 2D array (matrix)

z = np.zeros((3, 4))                    # 3x4 array of zeros
o = np.ones((2, 2))                     # 2x2 array of ones
r = np.arange(0, 10, 2)                 # [0, 2, 4, 6, 8] - like Python's range()
l = np.linspace(0, 1, 5)                # 5 evenly spaced numbers between 0 and 1

## Inspecting arrays

In [ ]:
a.shape      # dimensions, e.g. (4,) or (3, 4)
a.dtype      # data type, e.g. int64, float64
a.ndim       # number of dimensions (1, 2, 3...)
a.size       # total number of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Reshape

In [14]:
arr = np.arange(12)          # [0, 1, 2, ..., 11]
arr.reshape(3, 4)            # reshape into 3 rows, 4 columns
arr.reshape(3, 4).flatten()  # back to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Indexing & Slicing

In [15]:
arr = np.array([10, 20, 30, 40, 50])

arr[0]          # 10 (first element)
arr[-1]         # 50 (last element)
arr[1:4]        # [20, 30, 40] (slice, end excluded)
arr[:3]         # [10, 20, 30] (first 3)
arr[::-1]       # reversed array

array([50, 40, 30, 20, 10])

## 2D Indexing

In [16]:
m = np.array([[1, 2, 3], [4, 5, 6]])

m[0, 1]      # 2 → row 0, column 1
m[1, :]      # [4, 5, 6] → entire row 1
m[:, 0]      # [1, 4] → entire column 0

array([1, 4])

## Boolean Indexing


In [17]:
arr = np.array([5, 12, 8, 20, 3])
arr[arr > 10]          # [12, 20] — only values greater than 10
arr[(arr > 5) & (arr < 20)]   # combine conditions, same & rule as pandas

array([12,  8])

## Vectorized Operation

In [18]:
arr = np.array([1, 2, 3, 4])

arr + 5      # [6, 7, 8, 9]      - adds 5 to every element
arr * 2      # [2, 4, 6, 8]      - multiplies every element
arr ** 2     # [1, 4, 9, 16]     - squares every element

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
a + b        # [11, 22, 33]      - element-wise addition
a * b        # [10, 40, 90]      - element-wise multiplication

array([10, 40, 90])

## Agregation

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr.sum()        # 21 — sum of everything
arr.mean()       # 3.5
arr.std()        # standard deviation
arr.min()        # 1
arr.max()        # 6

## axis parameter
arr.sum(axis=0)   # sum DOWN each column → [5, 7, 9]
arr.sum(axis=1)   # sum ACROSS each row   → [6, 15]

## Conditional Logic

In [ ]:
## np.where(condition, value_if_true, value_if_false)

arr = np.array([3, 8, 1, 9, 5])
np.where(arr > 5, "High", "Low")

## Multicondition

In [ ]:
#df['Result'] = np.where(df['Winner'] == df['Team_1'], 1,
               #  np.where(df['Winner'] == df['Team_2'], 2, 0))

KeyError: 'Winner'

## np.select()

In [26]:
#conditions = [
   # df['Winner'] == df['Team_1'],
   # df['Winner'] == df['Team_2']
#]
#choices = [1, 2]

#df['Result'] = np.select(conditions, choices, default=0)

## Unique - find distinct value

In [28]:
arr = np.array([1, 2, 2, 3, 3,3, 3])
np.unique(arr)                          
# [1, 2, 3]

np.unique(arr, return_counts=True)      
# (array([1, 2, 3]), array([1, 2, 3]))

(array([1, 2, 3]), array([1, 2, 4]))

## Random

In [ ]:
#it generates 3 random number btw 0 and 1
np.random.rand(3) 

#it genrate random btw 2 any particular number and howmuch?
np.random.randint(0,10, size = 5)

array([4, 3, 6, 3, 4], dtype=int32)

## Seed

In [35]:
# it help to get the same random value again
np.random.seed(5)
print(np.random.randint(1, 10))

4
